apiVersion: v2
name: ckeditor-cs-stack
description: CKEditor Collaboration Server On-Premises stack installation

type: application
version: 0.1.0
appVersion: "3.11.0"

dependencies:
- name: ckeditor-cs
  version: "3.11.0"
  repository: "file://../ckeditor-cs"
- name: mysql
  condition: mysql.enabled
  version: "8.x.x"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  condition: redis.enabled
  version: "11.x.x"
  repository: "https://charts.bitnami.com/bitnami"
- name: common
  version: "0.x.x"
  repository: "https://charts.bitnami.com/bitnami"
