ckeditor-cs:
  secret:
    data:
      DATABASE_HOST: ckeditor-cs-mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: root-password
      REDIS_HOST: ckeditor-cs-redis-master
      ENVIRONMENTS_MANAGEMENT_SECRET_KEY: secret
      STORAGE_DRIVER: filesystem
      STORAGE_LOCATION: /var/cs/easyimage
      LICENSE_KEY:
  ingress:
    hosts:
      - host: ckeditor-cs.organization.test
        paths:
        - path: /

mysql:
  enabled: true
  image:
    tag: "5.7"
  auth:
    database: cs-on-premises
    auth: ckeditor-cs
    password: password
    rootPassword: root-password

redis:
  enabled: true
  cluster:
    enabled: true
  usePassword: false

common:
  names:
    fullname: ckeditor-cs
  capabilities:
    deployment:
      apiVersion: apps/v1
    statefulset:
      apiVersion: apps/v1
