{{- if .Values.worker.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckeditor-cs.worker.secretName" . }}
  labels:
    {{- include "ckeditor-cs.worker.labels" . | nindent 4 }}
{{- with .Values.worker.secret.data }}
stringData:

  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
