{{- if .Values.worker.enabled -}}
{{- if .Values.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ckeditor-cs.worker.serviceAccountName" . }}
  labels:
    {{- include "ckeditor-cs.worker.labels" . | nindent 4 }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
