ckeditor-cs:
  worker:
    enabled: true
    secret:
      data:
        DATABASE_HOST: ckeditor-cs-mysql
        DATABASE_USER: root
        DATABASE_PASSWORD: root-password
        REDIS_HOST: ckeditor-cs-redis-master
    resources:
      requests:
        cpu: 10m
        memory: 10Mi

  server:
    secret:
      data:
        DATABASE_HOST: ckeditor-cs-mysql
        DATABASE_USER: root
        DATABASE_PASSWORD: root-password
        REDIS_HOST: ckeditor-cs-redis-master
        ENVIRONMENTS_MANAGEMENT_SECRET_KEY: secret
        STORAGE_DRIVER: filesystem
        STORAGE_LOCATION: /var/cs/easyimage
        LICENSE_KEY:
    ingress:
      enabled: true
      hosts:
        - host: ckeditor-cs.organization.test
          paths:
          - path: /
    readinessProbe:
      initialDelaySeconds: 60
    resources:
      requests:
        cpu: 10m
        memory: 10Mi

mysql:
  enabled: true
  image:
    tag: "5.7"
  auth:
    database: cs-on-premises
    auth: ckeditor-cs
    password: password
    rootPassword: root-password
  commonLabels:
    app.kubernetes.io/part-of: ckeditor-cs

redis:
  enabled: true
  cluster:
    enabled: true
  usePassword: false
  commonLabels:
    app.kubernetes.io/part-of: ckeditor-cs

common:
  names:
    fullname: ckeditor-cs
  capabilities:
    deployment:
      apiVersion: apps/v1
    statefulset:
      apiVersion: apps/v1
